name: SAST
on:
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/sast.yml
  schedule:
    - cron: '0 0 * * 0'
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci --json -o ${{env.GITHUB_SHA}}results.json
      - name: Archive semgrep results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ${{env.GITHUB_SHA}}results.json

